add logout button and no more matches for pairing popup
SE701-T1/frontend pull request #137
Opened 2022-03-28 04:21 UTC by Xiaoqi510

## Description
1. Add a 'Log Out' button in src/components/NavBar/SideBar.jsx, so that users could be able to log out from the application. 
2. Add a ''NoBuddy' popup component in  src/components/NoBuddy/ , so that if a user has looped through all possible matches, the component will not immediately closing, it will say "no more matches".

Fixes #129 #84 

## How has this been tested?
manual testing

## Screenshots
*Provide screenshots of what has been implemented. Leave blank if not applicable*
<img width="823" alt="Screen Shot 2022-03-28 at 5 14 23 PM" src="https://user-images.githubusercontent.com/100509492/160325587-155e715b-1730-4afc-a1ac-0f845d1f718b.png">
<img width="244" alt="Screen Shot 2022-03-28 at 5 15 27 PM" src="https://user-images.githubusercontent.com/100509492/160325657-4679282f-e905-4d8d-83c5-59dc4d2d544d.png">

## Checklist
*(Leave blank if not applicable)*

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-03-28 05:42 UTC, christopher-alba requested changes
![image](https://user-images.githubusercontent.com/58793979/160333322-b651c9fb-ecf1-485d-8ea6-46c1c9117388.png)
Looking great! Just one thing to fix for the snapshot testing for the nav. I think you just have to delete the Nav.test.jsx.snap  under __snapshots__ folder and re-run the tests using ```npm test``` and it should generate a new snapshot :)

2022-03-28 06:44 UTC, Xiaoqi510 commented
> ![image](https://user-images.githubusercontent.com/58793979/160333322-b651c9fb-ecf1-485d-8ea6-46c1c9117388.png) Looking great! Just one thing to fix for the snapshot testing for the nav. I think you just have to delete the Nav.test.jsx.snap under **snapshots** folder and re-run the tests using `npm test` and it should generate a new snapshot :)

Thank you for your review, I modified it, please try **npm test** again

2022-03-28 22:29 UTC, christopher-alba requested changes
Heya, not sure if its just on my end but I think the library you are using is a little bugged. The styles are being removed once a file is uploaded to the dropzone for some reason. 
![image](https://user-images.githubusercontent.com/58793979/160497590-6c1bab28-7bd2-4afc-b79f-66ef757864c7.png)
I'm not too sure what you can do about this, maybe just use a standard file upload component.

2022-03-29 22:43 UTC, Xiaoqi510 commented
> Heya, not sure if its just on my end but I think the library you are using is a little bugged. The styles are being removed once a file is uploaded to the dropzone for some reason. ![image](https://user-images.githubusercontent.com/58793979/160497590-6c1bab28-7bd2-4afc-b79f-66ef757864c7.png) I'm not too sure what you can do about this, maybe just use a standard file upload component.

thank you for you suggestion, I change it from dropzone to input. please take a look

2022-03-29 22:57 UTC, christopher-alba commented on package.json
> +    "material-ui-dropzone": "^3.5.0",
Please uninstall the package using ```npm uninstall material-ui-dropzone``` command

2022-03-29 23:45 UTC, hpar461 commented
Code changes made to resolve issue #129 collide with code changes made in PR #139 and it will cause merge conflicts. It needs to be resolved.

2022-03-30 00:57 UTC, Xiaoqi510 commented
> Code changes made to resolve issue #129 collide with code changes made in PR #139 and it will cause merge conflicts. It needs to be resolved.

thank you for your mention, resolved the conflicts now

2022-03-30 01:17 UTC, christopher-alba commented on package-lock.json
> +        "material-ui-dropzone": "^3.5.0",
it seems the package-lock still has the dependencies of material-ui-dropzone installed, did you run the uninstall command or just delete it from the package.json?

2022-03-30 02:08 UTC, Xiaoqi510 commented
> Heya, not sure if its just on my end but I think the library you are using is a little bugged. The styles are being removed once a file is uploaded to the dropzone for some reason. ![image](https://user-images.githubusercontent.com/58793979/160497590-6c1bab28-7bd2-4afc-b79f-66ef757864c7.png) I'm not too sure what you can do about this, maybe just use a standard file upload component.

fixed

2022-03-30 02:08 UTC, Xiaoqi510 commented
> Heya, not sure if its just on my end but I think the library you are using is a little bugged. The styles are being removed once a file is uploaded to the dropzone for some reason. ![image](https://user-images.githubusercontent.com/58793979/160497590-6c1bab28-7bd2-4afc-b79f-66ef757864c7.png) I'm not too sure what you can do about this, maybe just use a standard file upload component.

fixed

2022-03-30 02:12 UTC, christopher-alba requested changes

2022-03-30 02:12 UTC, christopher-alba commented on src/pages/Upload/UploadPage.jsx
> +import styles from './UploadPopUp.module.css';
```suggestion
import styles from './UploadPage.module.css';
```
![image](https://user-images.githubusercontent.com/58793979/160736726-7240202f-7208-4722-bb19-6ad00532dd90.png)
I seem to be getting this error in the local environment, maybe try out this suggestion please.

2022-03-30 02:38 UTC, christopher-alba submitted a review, later dismissed
Nice work! LGTM!

2022-03-30 08:17 UTC, yuchendong13 submitted a review, later dismissed
LGTM!

2022-03-30 08:25 UTC, R055A requested changes
LGTM, aside for just one very small suggestion

2022-03-30 08:25 UTC, R055A commented on src/context/AuthContext.jsx
> +
```suggestion
```
This change is not required and adds an unecessary space after a comment

2022-03-30 11:59 UTC, Tvo465 submitted a review, later dismissed
Looks good. Nice work :)

2022-03-30 14:35 UTC, qzho236 approved these changes, later dismissed

2022-03-31 02:48 UTC, yuchendong13 approved these changes

2022-03-31 02:52 UTC, R055A approved these changes

2022-03-31 02:58 UTC, R055A commented on src/context/AuthContext.jsx
> +
Perfect. Thank you

2022-03-31 02:58 UTC, R055A commented
LGTM!

2022-03-31 05:50 UTC, christopher-alba approved these changes
Nice!

2022-03-31 05:50 UTC, merged