User search component
SE701-T1/frontend pull request #53
Opened 2022-03-14 11:29 UTC by sv-singh

## Description
This component allows users to type in the names of other users for searching.

Fixes issue #32 

## How has this been tested?
Tests are written to make sure each element is getting rendered correctly i.e. the search icon and placeholder text. There are also tests for ensuring the search icon is working correctly on click and also that the search updates correctly when entering text.

## Screenshots
![image](https://user-images.githubusercontent.com/69571529/158162298-2529e32b-19f3-42e9-964d-8f9cf759d42f.png)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-03-14 12:03 UTC, scorpionknifes requested changes
Great work.

_Couple suggested changes:_
tldr: remove `console.log` for testing, add props and simplications.
Also, remember to set up **prettier** and format your files thx.

2022-03-14 12:03 UTC, scorpionknifes commented on src/components/UserSearch/__tests__/UserSearch.test.jsx
> +        expect(console.log.mock.calls[0][0]).toBe("search pressed");
set a `jest.func()` and send it in as prop for `submitSearch`

Check if jest.func() is called when search is pressed.

2022-03-14 12:03 UTC, scorpionknifes commented on src/components/UserSearch/UserSearch.jsx
> +        onChange={(e) => searchItems(e.target.value)}
```suggestion
        onChange={handleSearch}
```
With the above simplifications

2022-03-14 12:51 UTC, sv-singh commented on src/components/UserSearch/UserSearch.jsx
> +  };
Thanks for the recommendations I've made those changes.

2022-03-14 22:59 UTC, scorpionknifes approved these changes
LGTM

2022-03-14 22:59 UTC, scorpionknifes commented on src/components/UserSearch/UserSearch.jsx
> +    width: '250px',
TODO: need to change this to be responsive. we can change this later when we make the buddy list.

2022-03-15 02:54 UTC, scorpionknifes approved these changes

2022-03-15 02:56 UTC, merged