Pairing page
SE701-T1/frontend pull request #86
Opened 2022-03-17 07:07 UTC by KirstyGong

## Description
Created a pairing page and connected to api

## How has this been tested?
tested with react test. Tests includes checking if course are rendered properly and the number of selected courses changed when a course is selected or unselected.

## Screenshots
![image](https://user-images.githubusercontent.com/66720955/158755029-020bab91-ac78-432a-ad73-0cc8ac59895c.png)

![image](https://user-images.githubusercontent.com/66720955/158755141-0f7474e9-44ea-46a6-8517-3427dd20e03f.png)

## Checklist
*(Leave blank if not applicable)*

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2022-03-17 12:15 UTC, conrad-scherb commented on src/pages/Pairing/Pairing.jsx
> +      setNumOfSelectedCourses(numOfSelectedCourses + 1);
These should probably become `setNumOfSelectedCourses(prev => prev+1)` (and -1 too)

2022-03-17 12:16 UTC, conrad-scherb requested changes
Few small fixes

2022-03-18 00:07 UTC, DanilLinkov approved these changes
Looks awesome, great job

2022-03-18 00:07 UTC, scorpionknifes approved these changes

2022-03-18 06:13 UTC, merged